#!/usr/bin/env python3
"""Publish a daily report to Google Sheets and grade prior calls.

    python scripts/publish_sheets.py reports/2026-08-12/report.json
    python scripts/publish_sheets.py reports/2026-08-12/report.json --dry-run

Writes three things to the spreadsheet named by GOOGLE_SHEET_ID:

  Today        this morning's ranked ideas, overwritten each run
  <date>       an immutable dated archive of the same content
  Performance  running scorecard of every idea ever published

Requires GCP_SERVICE_ACCOUNT_JSON (the whole key file, as a string) and
GOOGLE_SHEET_ID. The Sheet must be shared with the service account's
client_email as an Editor — that is the most common setup failure.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
STATE_PATH = REPO / "state" / "open_positions.json"
SCHEMA_PATH = REPO / "scripts" / "report_schema.json"

sys.path.insert(0, str(REPO / "scripts"))

HEADERS = [
    "#", "Instrument", "Symbol", "Class", "Venue", "Direction", "Horizon",
    "Conv", "Last", "Entry", "Entry Zone", "Target", "Target 2", "Stop",
    "R:R", "Size %", "Catalyst", "When (ET)", "Action / Timing", "Thesis",
    "Key Risk", "Sources",
]

PERF_HEADERS = [
    "Opened", "Instrument", "Symbol", "Venue", "Direction", "Horizon",
    "Entry", "Target", "Stop", "Status", "Last Price", "% vs Entry",
    "Days Open", "Closed", "Note",
]

DISCLAIMER = (
    "Automated research, not investment advice. Generated by an AI model from public data; "
    "it can be confidently wrong and prices may be stale. Futures are leveraged and can lose "
    "more than you deposit. You are responsible for every trade you place."
)

# Google Sheets colors are 0..1 floats, not 0..255 ints.
INK = {"red": 0.13, "green": 0.13, "blue": 0.15}
HEADER_BG = {"red": 0.16, "green": 0.19, "blue": 0.27}
WHITE = {"red": 1.0, "green": 1.0, "blue": 1.0}
GREEN = {"red": 0.85, "green": 0.94, "blue": 0.86}
RED = {"red": 0.98, "green": 0.87, "blue": 0.87}
AMBER = {"red": 1.0, "green": 0.95, "blue": 0.80}
GREY = {"red": 0.95, "green": 0.95, "blue": 0.96}

BULLISH = {"buy", "long", "yes"}
BEARISH = {"sell", "sell_short", "short", "no"}


# --------------------------------------------------------------------------
# formatting helpers
# --------------------------------------------------------------------------

def fmt_price(value: Any, unit: str = "usd") -> str:
    if value is None:
        return ""
    if unit == "cents":
        return f"{value:g}¢"
    if unit == "index_points":
        return f"{value:,.2f}"
    return f"${value:,.2f}" if value < 1000 else f"${value:,.0f}"


def fmt_zone(entry: dict, unit: str) -> str:
    lo, hi = entry.get("zone_low"), entry.get("zone_high")
    if lo is None or hi is None:
        return ""
    return f"{fmt_price(lo, unit)} – {fmt_price(hi, unit)}"


def direction_label(direction: str) -> str:
    return {
        "buy": "BUY", "sell": "SELL", "sell_short": "SHORT",
        "long": "LONG", "short": "SHORT", "yes": "YES", "no": "NO",
    }.get(direction, direction.upper())


def idea_row(idea: dict) -> list[Any]:
    unit = idea.get("unit", "usd")
    entry, exit_, cat = idea.get("entry", {}), idea.get("exit", {}), idea.get("catalyst", {})
    action = cat.get("action", "")
    if cat.get("wait"):
        action = f"⏸ WAIT — {action}"
    return [
        idea.get("rank", ""),
        idea.get("instrument", ""),
        idea.get("symbol", ""),
        idea.get("asset_class", "").upper(),
        idea.get("venue", "").replace("Robinhood ", "RH "),
        direction_label(idea.get("direction", "")),
        idea.get("horizon", ""),
        idea.get("conviction", ""),
        fmt_price(idea.get("last_price"), unit),
        fmt_price(entry.get("ideal"), unit),
        fmt_zone(entry, unit),
        fmt_price(exit_.get("target"), unit),
        fmt_price(exit_.get("target_2"), unit),
        fmt_price(idea.get("stop"), unit),
        f"{idea['risk_reward']:.1f}:1" if idea.get("risk_reward") else "",
        f"{idea['position_size_pct']:g}%" if idea.get("position_size_pct") else "",
        cat.get("event", ""),
        cat.get("datetime_et") or "",
        action,
        idea.get("thesis", ""),
        idea.get("key_risk", ""),
        "\n".join(idea.get("sources", [])[:4]),
    ]


def build_today_values(report: dict) -> tuple[list[list[Any]], int]:
    """Returns (rows, header_row_index_1based)."""
    ctx = report.get("market_context", {})
    levels = ctx.get("levels") or {}
    level_str = "  ·  ".join(f"{k.upper()} {v}" for k, v in levels.items() if v is not None)

    rows: list[list[Any]] = [
        [f"DAILY TRADE REPORT — {report.get('date', '')}"],
        [f"Generated {report.get('generated_at_et', '')}  ·  regime: {ctx.get('regime', 'unknown')}"
         + (f"  ·  ⚠ research truncated at cap" if report.get("truncated") else "")],
        [ctx.get("summary", "")],
        [level_str] if level_str else [""],
    ]

    cal = ctx.get("econ_calendar") or []
    if cal:
        rows.append([
            "CALENDAR:  " + "   |   ".join(
                f"{c.get('datetime_et', '')} {c.get('event', '')}"
                + (f" (cons. {c['consensus']})" if c.get("consensus") else "")
                for c in cal[:6]
            )
        ])

    rows.append([""])
    header_row = len(rows) + 1
    rows.append(HEADERS)

    ideas = sorted(report.get("recommendations", []), key=lambda i: i.get("rank", 99))
    rows.extend(idea_row(i) for i in ideas)

    watch = report.get("watchlist") or []
    if watch:
        rows.extend([[""], ["WATCHLIST — not yet actionable"]])
        for w in watch:
            rows.append([
                "", w.get("instrument", ""), w.get("symbol", ""), "", "", "", "", "", "", "", "",
                "", "", "", "", "", w.get("trigger", ""), "", "", w.get("note", ""), "", "",
            ])

    notes = report.get("data_quality_notes")
    if notes:
        rows.extend([[""], [f"DATA QUALITY: {notes}"]])
    rows.extend([[""], [DISCLAIMER]])
    return rows, header_row


# --------------------------------------------------------------------------
# performance grading
# --------------------------------------------------------------------------

def load_state() -> list[dict]:
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text() or "[]")
    return []


def save_state(positions: list[dict]) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(positions, indent=2) + "\n")


# Classes Yahoo can price, and therefore grade from daily bars. Event contracts
# have no free quote source and stay ungraded.
PRICEABLE = ("stock", "etf", "futures")


def _current_price(pos: dict) -> float | None:
    """Best-effort current price. None is an acceptable answer."""
    import market_data

    cls, symbol = pos.get("asset_class"), pos.get("symbol", "")
    try:
        if cls == "crypto":
            res = market_data.crypto([pos.get("coingecko_id") or symbol.lower()])
            if res.get("ok"):
                prices = list(res.get("prices", {}).values())
                return prices[0]["price"] if prices else None
            return None
        if cls in PRICEABLE:
            res = market_data.quote(symbol)
            return res.get("price") if res.get("ok") else None
    except Exception:  # noqa: BLE001 - grading must never break publishing
        return None
    return None


def grade_position(pos: dict, today: date) -> dict:
    """Update one open position in place-ish and return it."""
    if pos.get("status") not in (None, "open"):
        return pos

    opened = datetime.fromisoformat(pos["opened"]).date()
    pos["days_open"] = (today - opened).days

    entry = pos.get("entry")
    target = pos.get("target")
    stop = pos.get("stop")
    bullish = pos.get("direction") in BULLISH

    # Scan the bars since open so an intraday touch of the target or stop is
    # caught rather than only the closing price.
    if pos.get("asset_class") in PRICEABLE:
        try:
            import market_data

            hist = market_data.history(pos["symbol"], days=max(pos["days_open"] + 10, 20))
            if hist.get("ok"):
                for bar in hist.get("recent", []):
                    if bar["date"] <= opened.isoformat():
                        continue
                    hi, lo = bar["h"], bar["l"]
                    if target is not None and ((bullish and hi >= target) or (not bullish and lo <= target)):
                        pos.update(status="target_hit", closed=bar["date"], exit_price=target)
                        break
                    if stop is not None and ((bullish and lo <= stop) or (not bullish and hi >= stop)):
                        pos.update(status="stopped", closed=bar["date"], exit_price=stop)
                        break
        except Exception:  # noqa: BLE001
            pass

    last = pos.get("exit_price") or _current_price(pos)
    if last is not None:
        pos["last_price"] = last
        if entry:
            move = (last - entry) / entry * 100
            pos["pct_vs_entry"] = round(move if bullish else -move, 2)

    # Non-equity positions still resolve on the current print.
    if pos.get("status") in (None, "open") and last is not None:
        if target is not None and ((bullish and last >= target) or (not bullish and last <= target)):
            pos.update(status="target_hit", closed=today.isoformat(), exit_price=last)
        elif stop is not None and ((bullish and last <= stop) or (not bullish and last >= stop)):
            pos.update(status="stopped", closed=today.isoformat(), exit_price=last)

    # Time-box stale ideas so the tracker does not fill with zombies.
    # Long-term positions are meant to sit open for quarters, so expiring them
    # on a swing timetable would score every buy-and-hold thesis as a failure.
    max_days = {"intraday": 5, "swing": 45, "long_term": 730}.get(pos.get("horizon"), 45)
    if pos.get("status") in (None, "open") and pos["days_open"] > max_days:
        pos.update(status="expired", closed=today.isoformat())

    pos.setdefault("status", "open")
    return pos


def positions_from_report(report: dict) -> list[dict]:
    out = []
    for idea in report.get("recommendations", []):
        if (idea.get("catalyst") or {}).get("wait"):
            continue  # not entered today; nothing to track yet
        out.append({
            "opened": report["date"],
            "instrument": idea.get("instrument"),
            "symbol": idea.get("symbol"),
            "asset_class": idea.get("asset_class"),
            "venue": idea.get("venue"),
            "direction": idea.get("direction"),
            "horizon": idea.get("horizon"),
            "unit": idea.get("unit", "usd"),
            "entry": (idea.get("entry") or {}).get("ideal"),
            "target": (idea.get("exit") or {}).get("target"),
            "stop": idea.get("stop"),
            "conviction": idea.get("conviction"),
            "status": "open",
        })
    return out


def _price_note(pos: dict) -> str:
    if pos.get("asset_class") == "futures":
        # Yahoo quotes the continuous front-month, not the specific contract
        # month that was recommended, so the grade carries a basis error.
        base = "graded on continuous front-month; basis differs from the contract"
        return base if pos.get("last_price") is not None else f"{base}; price fetch failed"
    if pos.get("last_price") is not None:
        return ""
    if pos.get("asset_class") == "event":
        return "no free quote source for event contracts"
    return "price fetch failed this run"


def perf_row(pos: dict) -> list[Any]:
    unit = pos.get("unit", "usd")
    status = {
        "target_hit": "✓ TARGET", "stopped": "✗ STOPPED",
        "expired": "– EXPIRED", "open": "• OPEN",
    }.get(pos.get("status", "open"), pos.get("status", ""))
    pct = pos.get("pct_vs_entry")
    return [
        pos.get("opened", ""),
        pos.get("instrument", ""),
        pos.get("symbol", ""),
        (pos.get("venue") or "").replace("Robinhood ", "RH "),
        direction_label(pos.get("direction", "")),
        pos.get("horizon", ""),
        fmt_price(pos.get("entry"), unit),
        fmt_price(pos.get("target"), unit),
        fmt_price(pos.get("stop"), unit),
        status,
        fmt_price(pos.get("last_price"), unit),
        f"{pct:+.2f}%" if pct is not None else "",
        pos.get("days_open", ""),
        pos.get("closed", ""),
        pos.get("note") or _price_note(pos),
    ]


def summarize(positions: list[dict]) -> list[Any]:
    closed = [p for p in positions if p.get("status") in ("target_hit", "stopped", "expired")]
    wins = [p for p in closed if p.get("status") == "target_hit"]
    pcts = [p["pct_vs_entry"] for p in closed if p.get("pct_vs_entry") is not None]
    hit_rate = f"{len(wins) / len(closed) * 100:.0f}%" if closed else "—"
    avg = f"{sum(pcts) / len(pcts):+.2f}%" if pcts else "—"
    return [
        f"SCORECARD — {len(positions)} ideas tracked  ·  {len(closed)} closed  ·  "
        f"{len(wins)} hit target  ·  hit rate {hit_rate}  ·  avg move {avg}  ·  "
        f"{len([p for p in positions if p.get('status') == 'open'])} still open"
    ]


# --------------------------------------------------------------------------
# sheets io
# --------------------------------------------------------------------------

# Google's Sheets API returns these intermittently under load. They say nothing
# about credentials and clear on their own, so they are worth retrying rather
# than failing a morning over.
TRANSIENT_STATUS = {429, 500, 502, 503, 504}
AUTH_STATUS = {401, 403, 404}


def _status_code(exc: Exception) -> int | None:
    """Pull an HTTP status out of a gspread APIError, however it is carried."""
    code = getattr(getattr(exc, "response", None), "status_code", None)
    if code:
        return int(code)
    match = re.search(r"\[(\d{3})\]", str(exc))
    return int(match.group(1)) if match else None


def with_retry(fn: Any, what: str, attempts: int = 5) -> Any:
    """Retry `fn` through transient Google errors with exponential backoff."""
    delay = 2.0
    for attempt in range(1, attempts + 1):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001
            code = _status_code(exc)
            if code not in TRANSIENT_STATUS or attempt == attempts:
                raise
            print(f"  {what}: HTTP {code}, retrying in {delay:.0f}s "
                  f"(attempt {attempt}/{attempts})", file=sys.stderr)
            time.sleep(delay)
            delay *= 2
    raise RuntimeError("unreachable")


def open_spreadsheet():
    import gspread
    from google.oauth2.service_account import Credentials

    raw = os.environ.get("GCP_SERVICE_ACCOUNT_JSON", "").strip()
    sheet_id = os.environ.get("GOOGLE_SHEET_ID", "").strip()
    if not raw:
        raise SystemExit("GCP_SERVICE_ACCOUNT_JSON is not set")
    if not sheet_id:
        raise SystemExit("GOOGLE_SHEET_ID is not set")
    try:
        info = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"GCP_SERVICE_ACCOUNT_JSON is not valid JSON: {exc}") from exc

    creds = Credentials.from_service_account_info(
        info, scopes=["https://www.googleapis.com/auth/spreadsheets"]
    )
    client = gspread.authorize(creds)
    email = info.get("client_email")
    try:
        sheet = with_retry(lambda: client.open_by_key(sheet_id), "opening the spreadsheet")
        return sheet, email
    except Exception as exc:  # noqa: BLE001
        code = _status_code(exc)
        if code in AUTH_STATUS:
            raise SystemExit(
                f"Could not open sheet {sheet_id}: {exc}\n"
                f"HTTP {code} means the service account cannot reach this Sheet. "
                f"Share it with {email} as an Editor."
            ) from exc
        raise SystemExit(
            f"Could not open sheet {sheet_id} after retries: {exc}\n"
            f"HTTP {code} is a transient Google API failure, not a permissions problem — "
            f"the credentials and sharing are almost certainly fine. Re-run the workflow."
        ) from exc


def get_or_create(spreadsheet, title: str, rows: int, cols: int):
    """Fetch or create a tab, sized to hold `rows` x `cols`.

    Clearing a worksheet does not resize its grid, so a reused tab keeps
    whatever dimensions it was created with. Performance grows by a few rows
    every day and would eventually exceed them, failing the write with
    "exceeds grid limits" — so grow the grid explicitly when needed.
    """
    rows, cols = max(rows, 50), max(cols, 26)
    try:
        ws = spreadsheet.worksheet(title)
    except Exception:  # noqa: BLE001 - gspread raises WorksheetNotFound
        return spreadsheet.add_worksheet(title=title, rows=rows, cols=cols)

    ws.clear()
    if ws.row_count < rows or ws.col_count < cols:
        ws.resize(rows=max(rows, ws.row_count), cols=max(cols, ws.col_count))
    return ws


def style_grid(ws, header_row: int, n_cols: int, n_rows: int, ideas: list[dict]) -> None:
    """Header banding, direction tinting, and column widths in one batch."""
    sid = ws.id
    reqs: list[dict] = [
        {  # title
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": 0, "endRowIndex": 1},
                "cell": {"userEnteredFormat": {
                    "textFormat": {"bold": True, "fontSize": 14, "foregroundColor": INK}}},
                "fields": "userEnteredFormat.textFormat",
            }
        },
        {  # header band
            "repeatCell": {
                "range": {
                    "sheetId": sid,
                    "startRowIndex": header_row - 1, "endRowIndex": header_row,
                    "startColumnIndex": 0, "endColumnIndex": n_cols,
                },
                "cell": {"userEnteredFormat": {
                    "backgroundColor": HEADER_BG,
                    "textFormat": {"bold": True, "foregroundColor": WHITE, "fontSize": 10},
                    "verticalAlignment": "MIDDLE",
                    "horizontalAlignment": "CENTER",
                }},
                "fields": "userEnteredFormat(backgroundColor,textFormat,verticalAlignment,horizontalAlignment)",
            }
        },
        {"updateSheetProperties": {
            "properties": {"sheetId": sid, "gridProperties": {"frozenRowCount": header_row}},
            "fields": "gridProperties.frozenRowCount",
        }},
        {"updateDimensionProperties": {  # wrap the prose columns
            "range": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": 18, "endIndex": 22},
            "properties": {"pixelSize": 320},
            "fields": "pixelSize",
        }},
        {"updateDimensionProperties": {
            "range": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": 1, "endIndex": 2},
            "properties": {"pixelSize": 180},
            "fields": "pixelSize",
        }},
        {"repeatCell": {
            "range": {"sheetId": sid, "startRowIndex": header_row, "endRowIndex": n_rows,
                      "startColumnIndex": 16, "endColumnIndex": 22},
            "cell": {"userEnteredFormat": {"wrapStrategy": "WRAP", "verticalAlignment": "TOP"}},
            "fields": "userEnteredFormat(wrapStrategy,verticalAlignment)",
        }},
    ]

    # Tint the direction cell by side so the sheet is readable at a glance.
    for offset, idea in enumerate(ideas):
        row = header_row + offset
        d = idea.get("direction", "")
        bg = GREEN if d in BULLISH else RED if d in BEARISH else GREY
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": 5, "endColumnIndex": 6},
                "cell": {"userEnteredFormat": {
                    "backgroundColor": bg,
                    "textFormat": {"bold": True},
                    "horizontalAlignment": "CENTER",
                }},
                "fields": "userEnteredFormat(backgroundColor,textFormat,horizontalAlignment)",
            }
        })
        conv = idea.get("conviction") or 0
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": 7, "endColumnIndex": 8},
                "cell": {"userEnteredFormat": {
                    "backgroundColor": GREEN if conv >= 5 else AMBER if conv >= 4 else GREY,
                    "horizontalAlignment": "CENTER",
                    "textFormat": {"bold": True},
                }},
                "fields": "userEnteredFormat(backgroundColor,horizontalAlignment,textFormat)",
            }
        })

    ws.spreadsheet.batch_update({"requests": reqs})


def write_tab(spreadsheet, title: str, values: list[list[Any]], header_row: int, ideas: list[dict]):
    n_cols = max(len(r) for r in values)
    ws = with_retry(lambda: get_or_create(spreadsheet, title, len(values) + 10, n_cols + 2),
                    f"creating/clearing '{title}'")
    padded = [row + [""] * (n_cols - len(row)) for row in values]
    with_retry(lambda: ws.update(padded, "A1", value_input_option="RAW"), f"writing '{title}'")
    try:
        style_grid(ws, header_row, n_cols, len(values), ideas)
    except Exception as exc:  # noqa: BLE001 - content matters more than styling
        print(f"  warning: formatting failed on '{title}': {exc}", file=sys.stderr)
    return ws


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def validate(report: dict) -> None:
    try:
        import jsonschema
    except ImportError:
        print("  note: jsonschema not installed, skipping validation", file=sys.stderr)
        return
    jsonschema.validate(report, json.loads(SCHEMA_PATH.read_text()))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("report", type=Path)
    ap.add_argument("--dry-run", action="store_true", help="grade and render, but do not touch the Sheet")
    ap.add_argument("--skip-performance", action="store_true")
    args = ap.parse_args(argv)

    report = json.loads(args.report.read_text())
    validate(report)
    report_date = date.fromisoformat(report["date"])

    ideas = sorted(report.get("recommendations", []), key=lambda i: i.get("rank", 99))
    today_values, header_row = build_today_values(report)

    # Grade prior calls before appending today's, so a repeat idea does not
    # get graded against itself on the same run.
    positions = load_state()
    if not args.skip_performance:
        print(f"Grading {len([p for p in positions if p.get('status') == 'open'])} open positions...")
        positions = [grade_position(p, report_date) for p in positions]

    existing = {(p.get("opened"), p.get("symbol"), p.get("direction")) for p in positions}
    new = [p for p in positions_from_report(report) if
           (p["opened"], p["symbol"], p["direction"]) not in existing]
    positions.extend(new)
    print(f"Added {len(new)} new positions; {len(positions)} tracked in total.")

    perf_values = [
        ["PERFORMANCE TRACKER"],
        summarize(positions),
        [""],
        PERF_HEADERS,
    ]
    perf_values.extend(
        perf_row(p) for p in sorted(positions, key=lambda p: p.get("opened", ""), reverse=True)
    )

    if args.dry_run:
        print("\n--- DRY RUN: Today tab ---")
        for row in today_values[:header_row + len(ideas) + 2]:
            print("  " + " | ".join(str(c)[:28] for c in row))
        print("\n--- DRY RUN: Performance tab ---")
        for row in perf_values[:12]:
            print("  " + " | ".join(str(c)[:22] for c in row))
        save_state(positions)
        print(f"\nState written to {STATE_PATH.relative_to(REPO)}. Sheet not touched.")
        return 0

    # Persist before touching Sheets. Grading and capture are already done and do
    # not depend on the Sheet, so a Google outage should not also cost us the
    # position tracking — that would silently orphan a day of picks.
    save_state(positions)
    print(f"State saved to {STATE_PATH.relative_to(REPO)} ({len(positions)} positions).")

    spreadsheet, client_email = open_spreadsheet()
    print(f"Opened spreadsheet as {client_email}")

    write_tab(spreadsheet, "Today", today_values, header_row, ideas)
    print("  wrote 'Today'")

    write_tab(spreadsheet, report["date"], today_values, header_row, ideas)
    print(f"  wrote archive '{report['date']}'")

    write_tab(spreadsheet, "Performance", perf_values, 4, [])
    print("  wrote 'Performance'")

    # Keep Today and Performance at the front, archives behind them.
    try:
        order = ["Today", "Performance"]
        spreadsheet.reorder_worksheets(
            [spreadsheet.worksheet(t) for t in order]
            + [ws for ws in spreadsheet.worksheets() if ws.title not in order]
        )
    except Exception as exc:  # noqa: BLE001
        print(f"  warning: could not reorder tabs: {exc}", file=sys.stderr)

    print(f"Done. {len(ideas)} ideas published for {report['date']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
