#!/usr/bin/env python3
"""Publish a daily report to Google Sheets and grade prior calls.

    python scripts/publish_sheets.py reports/2026-08-12/report.json
    python scripts/publish_sheets.py reports/2026-08-12/report.json --dry-run

Writes three things to the spreadsheet named by GOOGLE_SHEET_ID:

  Today        this morning's ranked ideas, overwritten each run
  <date>       an immutable dated archive of the same content
  Performance  running scorecard of every idea ever published

Requires GCP_SERVICE_ACCOUNT_JSON (the whole key file, as a string) and
GOOGLE_SHEET_ID. The Sheet must be shared with the service account's
client_email as an Editor — that is the most common setup failure.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent
STATE_PATH = REPO / "state" / "open_positions.json"
SCHEMA_PATH = REPO / "scripts" / "report_schema.json"

sys.path.insert(0, str(REPO / "scripts"))

HEADERS = [
    "#", "Instrument", "Symbol", "Class", "Venue", "Direction", "Horizon",
    "Conv", "Last", "As of", "Entry", "Dist to Entry", "Entry Zone", "Target",
    "Target 2", "Stop", "R:R", "Size %", "Spread", "Catalyst", "When (ET)",
    "Action / Timing", "Thesis", "Key Risk", "Sources",
]

# Column indices that shift when HEADERS changes. Kept named so the styling
# below does not silently point at the wrong column after an edit.
COL_DIRECTION, COL_CONVICTION = 5, 7
COL_PROSE_START, COL_PROSE_END = 19, 25

PERF_HEADERS = [
    "Opened", "Instrument", "Symbol", "Class", "Venue", "Direction", "Horizon",
    "Conv", "Entry", "Entry Style", "Target", "Stop", "Status", "Graded",
    "Last Price", "% vs Entry", "Days Open", "Closed", "Note",
]


def _col(header: str) -> str:
    """Spreadsheet column letter for a Performance header, by name.

    Looked up rather than hardcoded so the formulas below cannot drift out of
    sync with the table when a column is inserted.
    """
    i = PERF_HEADERS.index(header)
    letter = ""
    while True:
        letter = chr(ord("A") + i % 26) + letter
        i = i // 26 - 1
        if i < 0:
            return letter


# Percent-points shown with a sign, e.g. +3.44%. Stored as the number 3.44 so
# AVERAGE and SUM read naturally, rather than as a Sheets percent (0.0344).
PCT_FORMAT = '+0.00"%";-0.00"%";0.00"%"'

# Wildcard-matched by the cumulative formulas, so no label may contain another
# as a substring.
STATUS_LABELS = {
    "pending": "◦ PENDING",
    "open": "• OPEN",
    "target_hit": "✓ TARGET",
    "stopped": "✗ STOPPED",
    "expired": "– EXPIRED",
    "not_filled": "⊘ NOFILL",
}

DISCLAIMER = (
    "Automated research, not investment advice. Generated by an AI model from public data; "
    "it can be confidently wrong and prices may be stale. Futures are leveraged and can lose "
    "more than you deposit. You are responsible for every trade you place."
)

# Google Sheets colors are 0..1 floats, not 0..255 ints.
INK = {"red": 0.13, "green": 0.13, "blue": 0.15}
HEADER_BG = {"red": 0.16, "green": 0.19, "blue": 0.27}
WHITE = {"red": 1.0, "green": 1.0, "blue": 1.0}
GREEN = {"red": 0.85, "green": 0.94, "blue": 0.86}
RED = {"red": 0.98, "green": 0.87, "blue": 0.87}
AMBER = {"red": 1.0, "green": 0.95, "blue": 0.80}
GREY = {"red": 0.95, "green": 0.95, "blue": 0.96}

BULLISH = {"buy", "long", "yes"}
BEARISH = {"sell", "sell_short", "short", "no"}


# --------------------------------------------------------------------------
# formatting helpers
# --------------------------------------------------------------------------

def fmt_price(value: Any, unit: str = "usd") -> str:
    if value is None:
        return ""
    if unit == "cents":
        return f"{value:g}¢"
    if unit == "index_points":
        return f"{value:,.2f}"
    return f"${value:,.2f}" if value < 1000 else f"${value:,.0f}"


def fmt_zone(entry: dict, unit: str) -> str:
    lo, hi = entry.get("zone_low"), entry.get("zone_high")
    if lo is None or hi is None:
        return ""
    return f"{fmt_price(lo, unit)} – {fmt_price(hi, unit)}"


def direction_label(direction: str) -> str:
    return {
        "buy": "BUY", "sell": "SELL", "sell_short": "SHORT",
        "long": "LONG", "short": "SHORT", "yes": "YES", "no": "NO",
    }.get(direction, direction.upper())


def _short_asof(raw: Any) -> str:
    """`2026-08-17T09:41:00-04:00` -> `08-17 09:41`. Empty when unknown."""
    if not raw:
        return ""
    text = str(raw)
    try:
        stamp = datetime.fromisoformat(text.replace("Z", "+00:00"))
        return stamp.strftime("%m-%d %H:%M")
    except ValueError:
        return text[:16]


def _spread_label(idea: dict) -> str:
    spread = (idea.get("validation") or {}).get("spread_pct")
    return f"{spread:.2f}%" if isinstance(spread, (int, float)) else ""


def idea_row(idea: dict) -> list[Any]:
    unit = idea.get("unit", "usd")
    entry, exit_, cat = idea.get("entry", {}), idea.get("exit", {}), idea.get("catalyst", {})
    action = cat.get("action", "")
    if cat.get("wait"):
        action = f"⏸ WAIT — {action}"
    return [
        idea.get("rank", ""),
        idea.get("instrument", ""),
        idea.get("symbol", ""),
        idea.get("asset_class", "").upper(),
        idea.get("venue", "").replace("Robinhood ", "RH "),
        direction_label(idea.get("direction", "")),
        idea.get("horizon", ""),
        idea.get("conviction", ""),
        fmt_price(idea.get("last_price"), unit),
        _short_asof(idea.get("last_price_asof")),
        fmt_price(entry.get("ideal"), unit),
        f"{idea['distance_to_entry_pct']:+.2f}%" if idea.get("distance_to_entry_pct") is not None else "",
        fmt_zone(entry, unit),
        fmt_price(exit_.get("target"), unit),
        fmt_price(exit_.get("target_2"), unit),
        fmt_price(idea.get("stop"), unit),
        f"{idea['risk_reward']:.1f}:1" if idea.get("risk_reward") else "",
        f"{idea['position_size_pct']:g}%" if idea.get("position_size_pct") else "",
        _spread_label(idea),
        cat.get("event", ""),
        cat.get("datetime_et") or "",
        action,
        idea.get("thesis", ""),
        idea.get("key_risk", ""),
        "\n".join(idea.get("sources", [])[:4]),
    ]


def build_today_values(report: dict, sectors: dict[str, str] | None = None) -> tuple[list[list[Any]], int, dict[str, Any]]:
    """Returns (rows, header_row_1based, style_spec).

    style_spec carries the 0-based row index of every idea and section banner,
    since section headers make the layout non-contiguous.
    """
    ctx = report.get("market_context", {})
    levels = ctx.get("levels") or {}
    level_str = "  ·  ".join(f"{k.upper()} {v}" for k, v in levels.items() if v is not None)

    rows: list[list[Any]] = [
        [f"DAILY TRADE REPORT — {report.get('date', '')}"],
        [f"Generated {report.get('generated_at_et', '')}  ·  regime: {ctx.get('regime', 'unknown')}"
         + (f"  ·  ⚠ research truncated at cap" if report.get("truncated") else "")],
        [ctx.get("summary", "")],
        [level_str] if level_str else [""],
    ]

    try:
        import exposure as _exposure
        rows.extend([[""]] + _exposure.render_rows(_exposure.summarize(report, sectors or {})))
    except Exception as exc:  # noqa: BLE001 - a nicety, never a blocker
        print(f"  warning: exposure summary failed: {exc}", file=sys.stderr)

    cal = ctx.get("econ_calendar") or []
    if cal:
        rows.append([
            "CALENDAR:  " + "   |   ".join(
                f"{c.get('datetime_et', '')} {c.get('event', '')}"
                + (f" (cons. {c['consensus']})" if c.get("consensus") else "")
                for c in cal[:6]
            )
        ])

    rows.append([""])
    header_row = len(rows) + 1
    rows.append(HEADERS)

    # Grouped by what you have to do this morning, not by rank. The first
    # question on opening this is "what do I act on now", and that is a
    # different set from "what is ranked highest" — six of eight ideas on a
    # typical day are waiting on a catalyst.
    ideas = sorted(report.get("recommendations", []), key=lambda i: i.get("rank", 99))
    act_now = [i for i in ideas if not (i.get("catalyst") or {}).get("wait")]
    waiting = [i for i in ideas if (i.get("catalyst") or {}).get("wait")]

    section_rows: list[int] = []          # 0-based row indices of section banners
    idea_rows: list[tuple[int, dict]] = []  # (0-based row index, idea)
    for label, group in (("▶ ACT TODAY", act_now), ("⏸ WAIT FOR THE CATALYST", waiting)):
        if not group:
            continue
        section_rows.append(len(rows))
        rows.append([f"{label}  ({len(group)})"])
        for idea in group:
            idea_rows.append((len(rows), idea))
            rows.append(idea_row(idea))

    watch = report.get("watchlist") or []
    if watch:
        rows.extend([[""], ["WATCHLIST — not yet actionable"]])
        for w in watch:
            rows.append([
                "", w.get("instrument", ""), w.get("symbol", ""), "", "", "", "", "", "", "",
                "", "", "", "", "", "", "", "", "", w.get("trigger", ""), "", "",
                w.get("note", ""), "", "",
            ])

    notes = report.get("data_quality_notes")
    if notes:
        rows.extend([[""], [f"DATA QUALITY: {notes}"]])
    rows.extend([[""], [DISCLAIMER]])
    return rows, header_row, {"ideas": idea_rows, "sections": section_rows}


# --------------------------------------------------------------------------
# performance grading
# --------------------------------------------------------------------------

def load_state() -> list[dict]:
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text() or "[]")
    return []


def save_state(positions: list[dict]) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(positions, indent=2) + "\n")


# Classes that can be priced, and therefore graded from daily bars. Event
# contracts have no free quote source and stay ungraded.
PRICEABLE = ("stock", "etf", "futures")

# CoinGecko is addressed by slug, not ticker. Looking up "btc" returns nothing,
# which is why every crypto position used to report a failed price fetch.
CRYPTO_SLUGS = {
    "BTC": "bitcoin", "XBT": "bitcoin", "ETH": "ethereum", "SOL": "solana",
    "XRP": "ripple", "DOGE": "dogecoin", "ADA": "cardano", "AVAX": "avalanche-2",
    "LINK": "chainlink", "DOT": "polkadot", "LTC": "litecoin", "BCH": "bitcoin-cash",
    "UNI": "uniswap", "SHIB": "shiba-inu", "AAVE": "aave", "XLM": "stellar",
    "ETC": "ethereum-classic", "USDC": "usd-coin", "MATIC": "matic-network",
    "PEPE": "pepe", "TRX": "tron", "NEAR": "near", "XTZ": "tezos",
}


def coingecko_id(symbol: str) -> str:
    """Ticker to CoinGecko slug, falling back to the lowercased ticker."""
    clean = (symbol or "").upper().replace("-USD", "").strip()
    return CRYPTO_SLUGS.get(clean, clean.lower())


def _current_price(pos: dict) -> float | None:
    """Best-effort current price. None is an acceptable answer."""
    import market_data

    cls, symbol = pos.get("asset_class"), pos.get("symbol", "")
    try:
        if cls == "crypto":
            res = market_data.crypto([pos.get("coingecko_id") or coingecko_id(symbol)])
            if res.get("ok"):
                prices = list(res.get("prices", {}).values())
                return prices[0]["price"] if prices else None
            return None
        if cls in PRICEABLE:
            res = market_data.quote(symbol)
            return res.get("price") if res.get("ok") else None
    except Exception:  # noqa: BLE001 - grading must never break publishing
        return None
    return None


# A setup is only a position once the market actually traded at its entry.
# Statuses, in the order a setup moves through them:
#   pending     published, entry never touched — not a position, no P&L
#   open        entry filled, live, marked to market from the fill
#   target_hit  target reached after the fill
#   stopped     stop reached after the fill
#   expired     filled but timed out with neither level reached
#   not_filled  timed out having never filled — excluded from P&L entirely
PENDING, OPEN, TARGET_HIT, STOPPED, EXPIRED, NOT_FILLED = (
    "pending", "open", "target_hit", "stopped", "expired", "not_filled")
LIVE_STATUSES = (None, PENDING, OPEN)
MAX_DAYS = {"intraday": 5, "swing": 45, "long_term": 730}

CLOSED_STATUSES = (TARGET_HIT, STOPPED, EXPIRED)

# Classes the scorecard cannot honestly measure, and therefore must not average
# over. Event contracts have no free quote source, so they never leave pending
# and would drag the fill rate down for a reason that is ours, not the market's.
# Futures are graded on Yahoo's continuous front-month rather than the contract
# that was actually recommended, so their percentage carries a basis error.
# Both stay in the detail table, flagged, and out of every figure above it.
UNGRADEABLE_CLASSES = {"event", "futures"}


def is_graded(pos: dict) -> bool:
    """Can this row's percentage be trusted enough to average over?"""
    return (pos.get("asset_class") or "") not in UNGRADEABLE_CLASSES


def entry_style(pos: dict) -> str:
    """Was the entry set below the market, above it, or at it?

    A `pullback` entry only fills when the trade first goes against the
    direction of the idea, which selects for the ideas that are already
    failing; a `breakout` entry only fills once the market confirms. Which of
    the two the report reaches for is a property worth measuring, so it sits in
    its own column rather than being inferred later.
    """
    entry, reference = pos.get("entry"), pos.get("reference_price")
    if entry is None or reference is None:
        return "unknown"
    if entry == reference:
        return "at-market"
    return "pullback" if ((entry < reference) == (pos.get("direction") in BULLISH)) else "breakout"


def _entry_filled(bar: dict, entry: float, reference: float | None) -> bool:
    """Did this bar trade at or through the entry level?

    Whether the entry sits above or below the market decides which side counts.
    An entry under the price at publication is a pullback limit, filled when the
    bar trades down to it; an entry above is a breakout, filled when the bar
    trades up to it. Without a reference price, fall back to the level simply
    being inside the bar's range.
    """
    low, high = bar["l"], bar["h"]
    if reference is None:
        return low <= entry <= high
    if entry < reference:
        return low <= entry
    if entry > reference:
        return high >= entry
    return low <= entry <= high


def _exit_hit(bar: dict, level: float, bullish: bool, is_target: bool) -> bool:
    """Directional test, so a bar that gaps clean past a level still counts."""
    favourable = bullish if is_target else not bullish
    return bar["h"] >= level if favourable else bar["l"] <= level


def _pnl_pct(entry: float | None, exit_price: float | None, bullish: bool) -> float | None:
    if not entry or exit_price is None:
        return None
    move = (exit_price - entry) / entry * 100
    return round(move if bullish else -move, 2)


def grade_position(pos: dict, today: date) -> dict:
    """Walk the bars in order: fill first, then exit. Never the other way round.

    The same symbol can appear on several rows from different days. Each is
    graded independently against its own entry, target and stop, from its own
    publication date, so two setups on one ticker resolve separately.
    """
    if pos.get("status") not in LIVE_STATUSES:
        return pos

    opened = datetime.fromisoformat(pos["opened"]).date()
    pos["days_since_published"] = (today - opened).days

    # A position is open only because a fill made it one. Rows written before
    # fills were tracked claim `open` with no fill behind them, and nothing
    # downstream ever demotes them, so they inflated the open count and the
    # fill rate indefinitely. Send them back to pending; the fill search below
    # promotes them again the moment a bar actually trades at the entry.
    if pos.get("status") == OPEN and not pos.get("filled_date"):
        pos["status"] = PENDING

    entry, target, stop = pos.get("entry"), pos.get("target"), pos.get("stop")
    bullish = pos.get("direction") in BULLISH
    reference = pos.get("reference_price")

    bars: list[dict] = []
    if pos.get("asset_class") in PRICEABLE and entry is not None:
        try:
            import market_data
            hist = market_data.history(
                pos["symbol"], days=max(pos["days_since_published"] + 10, 30))
            if hist.get("ok"):
                bars = [b for b in hist.get("recent", [])
                        if b.get("date") and b["date"] >= opened.isoformat()]
        except Exception:  # noqa: BLE001 - grading must never break publishing
            bars = []

    # 1. Find the fill. Everything downstream is measured from here.
    if not pos.get("filled_date") and bars and entry is not None:
        for bar in bars:
            if _entry_filled(bar, entry, reference):
                pos["filled_date"] = bar["date"]
                pos["fill_price"] = entry  # limit assumed filled at its level
                pos["status"] = OPEN
                break

    # 2. Only after a fill can a target or stop mean anything.
    if pos.get("filled_date") and pos.get("status") in (OPEN, None):
        after = [b for b in bars if b["date"] >= pos["filled_date"]]
        for bar in after:
            hit_target = target is not None and _exit_hit(bar, target, bullish, True)
            hit_stop = stop is not None and _exit_hit(bar, stop, bullish, False)
            # Both touched in one session and the intraday order is unknowable,
            # so assume the worse outcome rather than flattering the record.
            if hit_target and hit_stop:
                pos.update(status=STOPPED, closed=bar["date"], exit_price=stop)
                break
            if hit_target:
                pos.update(status=TARGET_HIT, closed=bar["date"], exit_price=target)
                break
            if hit_stop:
                pos.update(status=STOPPED, closed=bar["date"], exit_price=stop)
                break

    # 3. Classes with no bar history resolve on the current print instead.
    live = _current_price(pos)
    if live is not None:
        pos["last_price"] = live
    if not bars and entry is not None and live is not None:
        if not pos.get("filled_date") and _entry_filled(
                {"l": min(live, reference or live), "h": max(live, reference or live)},
                entry, reference):
            pos["filled_date"] = today.isoformat()
            pos["fill_price"] = entry
            pos["status"] = OPEN
        if pos.get("filled_date") and pos.get("status") in (OPEN, None):
            if target is not None and ((bullish and live >= target) or (not bullish and live <= target)):
                pos.update(status=TARGET_HIT, closed=today.isoformat(), exit_price=target)
            elif stop is not None and ((bullish and live <= stop) or (not bullish and live >= stop)):
                pos.update(status=STOPPED, closed=today.isoformat(), exit_price=stop)

    pos.setdefault("status", PENDING)

    # 4. P&L is measured from the fill, and only for setups that filled.
    if pos.get("filled_date"):
        opened_on = datetime.fromisoformat(pos["filled_date"]).date()
        pos["days_open"] = ((datetime.fromisoformat(pos["closed"]).date()
                             if pos.get("closed") else today) - opened_on).days
        mark = pos.get("exit_price") if pos.get("exit_price") is not None else pos.get("last_price")
        pos["pct_vs_entry"] = _pnl_pct(pos.get("fill_price") or entry, mark, bullish)
    else:
        pos["days_open"] = 0
        pos["pct_vs_entry"] = None

    # 5. Time-box, distinguishing "never got in" from "got in and it went cold".
    max_days = MAX_DAYS.get(pos.get("horizon"), 45)
    if pos.get("status") in (PENDING, OPEN) and pos["days_since_published"] > max_days:
        if pos.get("filled_date"):
            pos.update(status=EXPIRED, closed=today.isoformat())
        else:
            pos.update(status=NOT_FILLED, closed=today.isoformat())

    return pos


def positions_from_report(report: dict) -> list[dict]:
    out = []
    for idea in report.get("recommendations", []):
        if (idea.get("catalyst") or {}).get("wait"):
            continue  # not entered today; nothing to track yet
        out.append({
            "opened": report["date"],
            "instrument": idea.get("instrument"),
            "symbol": idea.get("symbol"),
            "asset_class": idea.get("asset_class"),
            "venue": idea.get("venue"),
            "direction": idea.get("direction"),
            "horizon": idea.get("horizon"),
            "unit": idea.get("unit", "usd"),
            "entry": (idea.get("entry") or {}).get("ideal"),
            "target": (idea.get("exit") or {}).get("target"),
            "stop": idea.get("stop"),
            "conviction": idea.get("conviction"),
            "position_size_pct": idea.get("position_size_pct"),
            "asset_class_note": None,
            # The report already priced this idea minutes ago. Carrying it over
            # means a position is marked to market from the day it opens rather
            # than showing an empty row until the next run.
            "last_price": idea.get("last_price"),
            "last_price_asof": idea.get("last_price_asof"),
            # The price when the idea was published decides whether the entry is
            # a pullback limit or a breakout, which decides how a fill is judged.
            "reference_price": idea.get("last_price"),
            "days_open": 0,
            "days_since_published": 0,
            "status": PENDING,
        })
    return out


def _price_note(pos: dict) -> str:
    status = pos.get("status")
    if status == PENDING:
        entry = pos.get("entry")
        return f"waiting for the market to reach {entry}" if entry else "waiting for entry"
    if status == NOT_FILLED:
        return "expired without ever trading at the entry — excluded from P&L"
    if pos.get("filled_date") and status == OPEN:
        return f"filled {pos['filled_date']}"
    if pos.get("asset_class") == "futures":
        # Yahoo quotes the continuous front-month, not the specific contract
        # month that was recommended, so the grade carries a basis error.
        base = "graded on continuous front-month; basis differs from the contract"
        return base if pos.get("last_price") is not None else f"{base}; price fetch failed"
    if pos.get("last_price") is not None:
        return ""
    if pos.get("asset_class") == "event":
        return "no free quote source for event contracts"
    return "price fetch failed this run"


def perf_row(pos: dict) -> list[Any]:
    unit = pos.get("unit", "usd")
    status = STATUS_LABELS.get(pos.get("status", PENDING), pos.get("status", ""))
    pct = pos.get("pct_vs_entry")
    return [
        pos.get("opened", ""),
        pos.get("instrument", ""),
        pos.get("symbol", ""),
        (pos.get("asset_class") or "").upper(),
        (pos.get("venue") or "").replace("Robinhood ", "RH "),
        direction_label(pos.get("direction", "")),
        pos.get("horizon", ""),
        pos.get("conviction", ""),
        fmt_price(pos.get("entry"), unit),
        entry_style(pos),
        fmt_price(pos.get("target"), unit),
        fmt_price(pos.get("stop"), unit),
        status,
        "yes" if is_graded(pos) else "no",
        fmt_price(pos.get("last_price"), unit),
        # Numeric, not text — the cumulative formulas aggregate this column.
        pct if pct is not None else "",
        # Blank rather than 0 for a setup that never filled, so the average
        # days-held figure is not diluted by rows that were never positions.
        pos.get("days_open", "") if pos.get("filled_date") else "",
        pos.get("closed", ""),
        pos.get("note") or _price_note(pos),
    ]


def _num(value: float | None, suffix: str = "%", signed: bool = True) -> str:
    if value is None:
        return "—"
    return f"{value:+.2f}{suffix}" if signed else f"{value:.2f}{suffix}"


# Offset within the cumulative block of the "Average per idea" row — the single
# figure that answers "how are these calls doing", so it is the one bolded.
# tests/test_publish_sheets.py asserts it still points at that row.
HEADLINE_OFFSET = 6


def compounded_return(positions: list[dict]) -> float | None:
    """Return on a book that took each closed idea in turn, full size, in order.

    The average per idea is what an equal-weight basket returned; this is the
    other honest question — what one unit of capital would have done running the
    closed trades sequentially. Neither is a sum of percentages, which is what
    this scorecard used to print and which is not a return at all: it grows with
    the number of ideas published rather than with how well they did.
    """
    graded = [p for p in positions
              if is_graded(p) and p.get("status") in CLOSED_STATUSES
              and p.get("pct_vs_entry") is not None]
    if not graded:
        return None
    equity = 1.0
    for pos in sorted(graded, key=lambda p: (p.get("closed") or "", p.get("opened") or "")):
        equity *= 1 + pos["pct_vs_entry"] / 100
    return round((equity - 1) * 100, 2)


def cumulative_rows(positions: list[dict], first_row: int) -> tuple[list[list[Any]], list[tuple[int, int, str]]]:
    """Portfolio figures as live spreadsheet formulas.

    `first_row` is the 1-based sheet row where the position detail begins. Every
    range is left open-ended (`P25:P` rather than `P25:P43`) so the figures pick
    up rows added by a later run, or typed in by hand, without anything being
    regenerated.

    Every figure is equal-weighted — one unit per published idea — because the
    report cannot know what size was actually traded. It measures the calls, not
    an account.

    Two rules run through all of it:

    * **Only graded rows count.** Event contracts have no quote source and
      futures are marked against the wrong contract month, so averaging over
      them would report a number nobody can act on. They stay in the detail
      table, flagged `no`, and out of every figure here.
    * **Closed means closed.** These tables used to derive it as
      `ideas - open`, which quietly counted every setup still waiting for its
      entry as a closed trade — with 22 pending rows that turned 10 closed
      trades into 32 and made every breakdown average wrong.
    """
    if not positions:
        return [], []

    def rng(header: str) -> str:
        col = _col(header)
        return f"${col}${first_row}:${col}"

    cls, hor, conv = rng("Class"), rng("Horizon"), rng("Conv")
    side, stat, pct = rng("Direction"), rng("Status"), rng("% vs Entry")
    days, style, graded = rng("Days Open"), rng("Entry Style"), rng("Graded")

    # Prepended to every criteria list, so no figure below can accidentally
    # average over a row this report cannot price honestly.
    G = f'{graded},"yes"'

    n_all = f"COUNTIF({graded},\"yes\")"
    n_open = f'COUNTIFS({G},{stat},"*OPEN*")'
    n_pending = f'COUNTIFS({G},{stat},"*PENDING*")'
    n_nofill = f'COUNTIFS({G},{stat},"*NOFILL*")'
    n_target = f'COUNTIFS({G},{stat},"*TARGET*")'
    n_stopped = f'COUNTIFS({G},{stat},"*STOPPED*")'
    n_expired = f'COUNTIFS({G},{stat},"*EXPIRED*")'
    n_closed = f"({n_target}+{n_stopped}+{n_expired})"
    # Built up from the statuses that mean a fill happened, rather than
    # subtracted from the total, so a status added later cannot silently land
    # on the wrong side of this line.
    n_filled = f"({n_open}+{n_closed})"
    # Rows carrying an actual mark. An open position whose price fetch failed
    # counts as filled but must not dilute an average as if it were flat.
    n_marked = f'COUNTIFS({G},{pct},"<>")'

    unreal_sum = f'SUMIFS({pct},{G},{stat},"*OPEN*")'
    real_sum = f"(SUMIFS({pct},{G})-{unreal_sum})"

    rows: list[list[Any]] = []
    formats: list[tuple[int, int, str]] = []

    def add(cells: list[Any], fmt: dict[int, str] | None = None) -> None:
        for col, kind in (fmt or {}).items():
            formats.append((len(rows), col, kind))
        rows.append(cells)

    add([""])
    add(["CUMULATIVE PERFORMANCE — live formulas, equal weight, one unit per idea"])
    add([f'=CONCATENATE("Graded setups: ",{n_all},"   ·   filled and open: ",{n_open},'
         f'"   ·   closed: ",{n_closed},"   ·   awaiting entry: ",{n_pending},'
         f'"   ·   never filled: ",{n_nofill},'
         f'"   ·   ungraded (event / futures): ",COUNTIF({graded},"no"))'])
    add(["A setup becomes a position only once the market trades at its entry. Awaiting-entry "
         "and never-filled rows carry no P&L. Event contracts and futures are excluded from "
         "every figure here — see the Graded column."])
    add([""])

    add(["", "Realized (closed)", "Unrealized (open)", "Combined"])
    add(["Average per idea — the equal-weight return",
         f'=IFERROR({real_sum}/{n_closed},"—")',
         f'=IFERROR(AVERAGEIFS({pct},{G},{stat},"*OPEN*"),"—")',
         f'=IFERROR(SUMIFS({pct},{G})/{n_marked},"—")'],
        {1: "pct", 2: "pct", 3: "pct"})
    # Static, not a formula: sequencing closed trades by their close date is not
    # something an open-ended range can express. Recomputed on every publish.
    add(["Compounded, closed trades taken one at a time",
         _num(compounded_return(positions))])
    # MAXIFS/MINIFS rather than MAX/MIN: a futures row marked against the wrong
    # contract month would otherwise walk off with "best idea so far".
    add(["Best / worst idea so far",
         f'=IFERROR(MAXIFS({pct},{G}),"—")', f'=IFERROR(MINIFS({pct},{G}),"—")'],
        {1: "pct", 2: "pct"})
    add([""])
    add(["Hit rate (closed that reached target)",
         f'=IFERROR({n_target}/{n_closed},"—")'], {1: "rate"})
    add(["Closed: target / stopped / expired",
         f"={n_target}", f"={n_stopped}", f"={n_expired}"])
    add(["Open positions up / down",
         f'=COUNTIFS({G},{stat},"*OPEN*",{pct},">0")',
         f'=COUNTIFS({G},{stat},"*OPEN*",{pct},"<0")'])
    # Days Open is written blank for a setup that never filled, so this averages
    # over positions rather than over publications. It used to divide by every
    # row in the table, which turned 5.7 days held into 2.4.
    add(["Average days held (filled positions only)",
         f'=IFERROR(AVERAGEIFS({days},{G}),"—")'])
    add([""])

    # ---- fill quality ----------------------------------------------------
    # The entry level decides which ideas you are ever in a position to be
    # right about. A pullback entry fills only once the trade has first gone
    # against you, so a book made of them is selected for the ideas that were
    # already failing — visible here as a fill rate and an average move that
    # differ by style.
    add(["FILL QUALITY — which ideas the entry level actually lets you into"])
    add(["Fill rate (setups that reached their entry)",
         f'=IFERROR({n_filled}/{n_all},"—")'], {1: "rate"})
    add(["Still awaiting entry / expired never having filled",
         f"={n_pending}", f"={n_nofill}"])
    add(["", "Setups", "Filled", "Fill rate", "Avg move"])
    for label in ("pullback", "breakout", "at-market"):
        key = f'"{label}"'
        setups = f"COUNTIFS({G},{style},{key})"
        filled = (f'(COUNTIFS({G},{style},{key},{stat},"*OPEN*")'
                  f'+COUNTIFS({G},{style},{key},{stat},"*TARGET*")'
                  f'+COUNTIFS({G},{style},{key},{stat},"*STOPPED*")'
                  f'+COUNTIFS({G},{style},{key},{stat},"*EXPIRED*"))')
        add([label, f"={setups}", f"={filled}",
             f'=IFERROR({filled}/{setups},"—")',
             f'=IFERROR(AVERAGEIFS({pct},{G},{style},{key}),"—")'],
            {3: "rate", 4: "pct"})
    add([""])

    # ---- breakdowns ------------------------------------------------------
    # Buckets come from the data present today; the formulas inside them stay
    # live, so a row edited later still moves these numbers.
    def breakdown(label: str, target_rng: str, values: list[Any]) -> None:
        if len(values) < 2:
            return
        add([f"BY {label.upper()}"])
        add(["", "Ideas", "Closed", "Hit rate", "Avg realized", "Avg unrealized", "Avg per idea"])
        for value in values:
            key = f'"{value}"'
            where = f"{G},{target_rng},{key}"
            closed = (f'(COUNTIFS({where},{stat},"*TARGET*")'
                      f'+COUNTIFS({where},{stat},"*STOPPED*")'
                      f'+COUNTIFS({where},{stat},"*EXPIRED*"))')
            open_sum = f'SUMIFS({pct},{where},{stat},"*OPEN*")'
            add([
                str(value),
                f"=COUNTIFS({where})",
                f"={closed}",
                f'=IFERROR(COUNTIFS({where},{stat},"*TARGET*")/{closed},"—")',
                f'=IFERROR((SUMIFS({pct},{where})-{open_sum})/{closed},"—")',
                f'=IFERROR(AVERAGEIFS({pct},{where},{stat},"*OPEN*"),"—")',
                f'=IFERROR(SUMIFS({pct},{where})/COUNTIFS({where},{pct},"<>"),"—")',
            ], {3: "rate", 4: "pct", 5: "pct", 6: "pct"})
        add([""])

    gradeable = [p for p in positions if is_graded(p)]

    def distinct(key: str, transform=lambda v: v) -> list[Any]:
        seen = {transform(p.get(key)) for p in gradeable if p.get(key) is not None}
        return sorted(seen, key=str)

    breakdown("horizon", hor, distinct("horizon"))
    breakdown("asset class", cls, distinct("asset_class", lambda v: str(v).upper()))
    breakdown("conviction", conv, distinct("conviction"))
    breakdown("direction", side, distinct("direction", direction_label))

    add(["Equal-weighted percentage moves against each idea's published entry, graded from "
         "daily bars. These measure the calls, not any account — no sizing, no slippage, no "
         "fees. Averages, never sums: a sum of percentages grows with how many ideas were "
         "published rather than with how they did. Formulas read the detail table below, so "
         "editing or adding a row updates every figure above."])
    return rows, formats


def summarize(positions: list[dict]) -> list[Any]:
    graded = [p for p in positions if is_graded(p)]
    closed = [p for p in graded if p.get("status") in CLOSED_STATUSES]
    wins = [p for p in closed if p.get("status") == TARGET_HIT]
    pcts = [p["pct_vs_entry"] for p in closed if p.get("pct_vs_entry") is not None]
    hit_rate = f"{len(wins) / len(closed) * 100:.0f}%" if closed else "—"
    avg = f"{sum(pcts) / len(pcts):+.2f}%" if pcts else "—"
    # A thesis re-pitched on four mornings is four rows here but one call, and
    # the difference is large enough to change how the averages read. The rows
    # stay independent — each has its own levels and grades on its own merits —
    # but the count says out loud how many distinct calls are behind them.
    theses = {(p.get("symbol"), p.get("direction")) for p in graded}
    return [
        f"SCORECARD — {len(graded)} graded rows from {len(theses)} distinct theses  ·  "
        f"{len(closed)} closed  ·  {len(wins)} hit target  ·  hit rate {hit_rate}  ·  "
        f"avg move per closed idea {avg}  ·  "
        f"{len([p for p in graded if p.get('status') == OPEN])} still open"
    ]


# --------------------------------------------------------------------------
# sheets io
# --------------------------------------------------------------------------

# Google's Sheets API returns these intermittently under load. They say nothing
# about credentials and clear on their own, so they are worth retrying rather
# than failing a morning over.
TRANSIENT_STATUS = {429, 500, 502, 503, 504}
AUTH_STATUS = {401, 403, 404}


def _status_code(exc: Exception) -> int | None:
    """Pull an HTTP status out of a gspread APIError, however it is carried."""
    code = getattr(getattr(exc, "response", None), "status_code", None)
    if code:
        return int(code)
    match = re.search(r"\[(\d{3})\]", str(exc))
    return int(match.group(1)) if match else None


def with_retry(fn: Any, what: str, attempts: int = 5) -> Any:
    """Retry `fn` through transient Google errors with exponential backoff."""
    delay = 2.0
    for attempt in range(1, attempts + 1):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001
            code = _status_code(exc)
            if code not in TRANSIENT_STATUS or attempt == attempts:
                raise
            print(f"  {what}: HTTP {code}, retrying in {delay:.0f}s "
                  f"(attempt {attempt}/{attempts})", file=sys.stderr)
            time.sleep(delay)
            delay *= 2
    raise RuntimeError("unreachable")


def open_spreadsheet():
    import gspread
    from google.oauth2.service_account import Credentials

    raw = os.environ.get("GCP_SERVICE_ACCOUNT_JSON", "").strip()
    sheet_id = os.environ.get("GOOGLE_SHEET_ID", "").strip()
    if not raw:
        raise SystemExit("GCP_SERVICE_ACCOUNT_JSON is not set")
    if not sheet_id:
        raise SystemExit("GOOGLE_SHEET_ID is not set")
    try:
        info = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"GCP_SERVICE_ACCOUNT_JSON is not valid JSON: {exc}") from exc

    creds = Credentials.from_service_account_info(
        info, scopes=["https://www.googleapis.com/auth/spreadsheets"]
    )
    client = gspread.authorize(creds)
    email = info.get("client_email")
    try:
        sheet = with_retry(lambda: client.open_by_key(sheet_id), "opening the spreadsheet")
        return sheet, email
    except Exception as exc:  # noqa: BLE001
        code = _status_code(exc)
        if code in AUTH_STATUS:
            raise SystemExit(
                f"Could not open sheet {sheet_id}: {exc}\n"
                f"HTTP {code} means the service account cannot reach this Sheet. "
                f"Share it with {email} as an Editor."
            ) from exc
        raise SystemExit(
            f"Could not open sheet {sheet_id} after retries: {exc}\n"
            f"HTTP {code} is a transient Google API failure, not a permissions problem — "
            f"the credentials and sharing are almost certainly fine. Re-run the workflow."
        ) from exc


def get_or_create(spreadsheet, title: str, rows: int, cols: int):
    """Fetch or create a tab, sized to hold `rows` x `cols`.

    Clearing a worksheet does not resize its grid, so a reused tab keeps
    whatever dimensions it was created with. Performance grows by a few rows
    every day and would eventually exceed them, failing the write with
    "exceeds grid limits" — so grow the grid explicitly when needed.
    """
    rows, cols = max(rows, 50), max(cols, 26)
    try:
        ws = spreadsheet.worksheet(title)
    except Exception:  # noqa: BLE001 - gspread raises WorksheetNotFound
        return spreadsheet.add_worksheet(title=title, rows=rows, cols=cols)

    ws.clear()
    if ws.row_count < rows or ws.col_count < cols:
        ws.resize(rows=max(rows, ws.row_count), cols=max(cols, ws.col_count))
    return ws


def style_grid(ws, header_row: int, n_cols: int, n_rows: int, spec: dict[str, Any]) -> None:
    """Header banding, direction tinting, and column widths in one batch."""
    sid = ws.id
    reqs: list[dict] = [
        {  # title
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": 0, "endRowIndex": 1},
                "cell": {"userEnteredFormat": {
                    "textFormat": {"bold": True, "fontSize": 14, "foregroundColor": INK}}},
                "fields": "userEnteredFormat.textFormat",
            }
        },
        {  # header band
            "repeatCell": {
                "range": {
                    "sheetId": sid,
                    "startRowIndex": header_row - 1, "endRowIndex": header_row,
                    "startColumnIndex": 0, "endColumnIndex": n_cols,
                },
                "cell": {"userEnteredFormat": {
                    "backgroundColor": HEADER_BG,
                    "textFormat": {"bold": True, "foregroundColor": WHITE, "fontSize": 10},
                    "verticalAlignment": "MIDDLE",
                    "horizontalAlignment": "CENTER",
                }},
                "fields": "userEnteredFormat(backgroundColor,textFormat,verticalAlignment,horizontalAlignment)",
            }
        },
        {"updateSheetProperties": {
            "properties": {"sheetId": sid, "gridProperties": {"frozenRowCount": header_row}},
            "fields": "gridProperties.frozenRowCount",
        }},
        {"updateDimensionProperties": {  # wrap the prose columns
            "range": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": COL_PROSE_START + 2, "endIndex": COL_PROSE_END},
            "properties": {"pixelSize": 320},
            "fields": "pixelSize",
        }},
        {"updateDimensionProperties": {
            "range": {"sheetId": sid, "dimension": "COLUMNS", "startIndex": 1, "endIndex": 2},
            "properties": {"pixelSize": 180},
            "fields": "pixelSize",
        }},
        {"repeatCell": {
            "range": {"sheetId": sid, "startRowIndex": header_row, "endRowIndex": n_rows,
                      "startColumnIndex": COL_PROSE_START, "endColumnIndex": COL_PROSE_END},
            "cell": {"userEnteredFormat": {"wrapStrategy": "WRAP", "verticalAlignment": "TOP"}},
            "fields": "userEnteredFormat(wrapStrategy,verticalAlignment)",
        }},
    ]

    # Section banners: dark bar across the width so the eye finds them.
    for row in spec.get("sections", []):
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": 0, "endColumnIndex": n_cols},
                "cell": {"userEnteredFormat": {
                    "backgroundColor": HEADER_BG,
                    "textFormat": {"bold": True, "foregroundColor": WHITE, "fontSize": 11},
                }},
                "fields": "userEnteredFormat(backgroundColor,textFormat)",
            }
        })

    # Tint the direction cell by side so the sheet is readable at a glance.
    for row, idea in spec.get("ideas", []):
        d = idea.get("direction", "")
        bg = GREEN if d in BULLISH else RED if d in BEARISH else GREY
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": COL_DIRECTION, "endColumnIndex": COL_DIRECTION + 1},
                "cell": {"userEnteredFormat": {
                    "backgroundColor": bg,
                    "textFormat": {"bold": True},
                    "horizontalAlignment": "CENTER",
                }},
                "fields": "userEnteredFormat(backgroundColor,textFormat,horizontalAlignment)",
            }
        })
        conv = idea.get("conviction") or 0
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": COL_CONVICTION, "endColumnIndex": COL_CONVICTION + 1},
                "cell": {"userEnteredFormat": {
                    "backgroundColor": GREEN if conv >= 5 else AMBER if conv >= 4 else GREY,
                    "horizontalAlignment": "CENTER",
                    "textFormat": {"bold": True},
                }},
                "fields": "userEnteredFormat(backgroundColor,horizontalAlignment,textFormat)",
            }
        })

    ws.spreadsheet.batch_update({"requests": reqs})


def style_performance(ws, formats: list[tuple[int, int, str]], block_start: int,
                      detail_first_row: int, total_rows: int) -> None:
    """Number formats for the cumulative block and the percent column."""
    sid = ws.id
    patterns = {
        "pct": {"type": "NUMBER", "pattern": PCT_FORMAT},
        "rate": {"type": "PERCENT", "pattern": "0.0%"},
    }
    reqs = [{
        "repeatCell": {
            "range": {"sheetId": sid, "startRowIndex": detail_first_row - 1,
                      "startColumnIndex": PERF_HEADERS.index("% vs Entry"),
                      "endColumnIndex": PERF_HEADERS.index("% vs Entry") + 1},
            "cell": {"userEnteredFormat": {"numberFormat": patterns["pct"]}},
            "fields": "userEnteredFormat.numberFormat",
        }
    }]
    for offset, col, kind in formats:
        row = block_start + offset
        if row >= total_rows:
            continue
        reqs.append({
            "repeatCell": {
                "range": {"sheetId": sid, "startRowIndex": row, "endRowIndex": row + 1,
                          "startColumnIndex": col, "endColumnIndex": col + 1},
                "cell": {"userEnteredFormat": {
                    "numberFormat": patterns[kind],
                    # The headline average is the row people read first.
                    "textFormat": {"bold": kind == "pct" and offset == HEADLINE_OFFSET},
                }},
                "fields": "userEnteredFormat(numberFormat,textFormat)",
            }
        })
    reqs.append({
        "repeatCell": {
            "range": {"sheetId": sid, "startRowIndex": block_start + 1,
                      "endRowIndex": block_start + 2},
            "cell": {"userEnteredFormat": {"textFormat": {"bold": True, "fontSize": 11}}},
            "fields": "userEnteredFormat.textFormat",
        }
    })
    ws.spreadsheet.batch_update({"requests": reqs})


def write_tab(spreadsheet, title: str, values: list[list[Any]], header_row: int,
              spec: dict[str, Any] | None = None, value_input_option: str = "RAW"):
    n_cols = max(len(r) for r in values)
    ws = with_retry(lambda: get_or_create(spreadsheet, title, len(values) + 10, n_cols + 2),
                    f"creating/clearing '{title}'")
    padded = [row + [""] * (n_cols - len(row)) for row in values]
    with_retry(lambda: ws.update(padded, "A1", value_input_option=value_input_option),
               f"writing '{title}'")
    if spec is not None:
        try:
            style_grid(ws, header_row, n_cols, len(values), spec)
        except Exception as exc:  # noqa: BLE001 - content matters more than styling
            print(f"  warning: formatting failed on '{title}': {exc}", file=sys.stderr)
    return ws


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def validate(report: dict) -> None:
    try:
        import jsonschema
    except ImportError:
        print("  note: jsonschema not installed, skipping validation", file=sys.stderr)
        return
    jsonschema.validate(report, json.loads(SCHEMA_PATH.read_text()))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("report", type=Path)
    ap.add_argument("--dry-run", action="store_true", help="grade and render, but do not touch the Sheet")
    ap.add_argument("--skip-performance", action="store_true")
    args = ap.parse_args(argv)

    report = json.loads(args.report.read_text())
    validate(report)
    report_date = date.fromisoformat(report["date"])

    ideas = sorted(report.get("recommendations", []), key=lambda i: i.get("rank", 99))
    sectors = {}
    if not args.dry_run:
        try:
            import exposure as _exposure
            sectors = _exposure.fetch_sectors(ideas)
        except Exception as exc:  # noqa: BLE001
            print(f"  note: sector lookup unavailable: {exc}", file=sys.stderr)
    today_values, header_row, style_spec = build_today_values(report, sectors)

    # Grade prior calls before appending today's, so a repeat idea does not
    # get graded against itself on the same run.
    positions = load_state()
    if not args.skip_performance:
        print(f"Grading {len([p for p in positions if p.get('status') == 'open'])} open positions...")
        positions = [grade_position(p, report_date) for p in positions]

    # Keyed on entry as well as date, so the same ticker recommended twice with
    # different levels stays two independently graded rows.
    def key(p: dict) -> tuple:
        return (p.get("opened"), p.get("symbol"), p.get("direction"), p.get("entry"))

    existing = {key(p) for p in positions}
    new = [p for p in positions_from_report(report) if key(p) not in existing]
    positions.extend(new)
    print(f"Added {len(new)} new positions; {len(positions)} tracked in total.")

    # Two passes: the block's height is independent of where the detail table
    # starts, so measure it, then regenerate with the real row references.
    PREAMBLE = 2          # title + scorecard
    BETWEEN = 3           # blank, "POSITION DETAIL", header row
    block, _ = cumulative_rows(positions, 1)
    detail_first_row = PREAMBLE + len(block) + BETWEEN + 1
    block, perf_formats = cumulative_rows(positions, detail_first_row)

    perf_values = [["PERFORMANCE TRACKER"], summarize(positions)]
    perf_values.extend(block)
    perf_values.extend([[""], ["POSITION DETAIL"], PERF_HEADERS])
    # 0-based sheet row where the block begins, for the formatting pass.
    block_start = PREAMBLE
    perf_values.extend(
        perf_row(p) for p in sorted(positions, key=lambda p: p.get("opened", ""), reverse=True)
    )

    if args.dry_run:
        print("\n--- DRY RUN: Today tab ---")
        for row in today_values[:header_row + len(ideas) + 2]:
            print("  " + " | ".join(str(c)[:28] for c in row))
        print("\n--- DRY RUN: Performance tab ---")
        for row in perf_values[:12]:
            print("  " + " | ".join(str(c)[:22] for c in row))
        save_state(positions)
        print(f"\nState written to {STATE_PATH.relative_to(REPO)}. Sheet not touched.")
        return 0

    # Persist before touching Sheets. Grading and capture are already done and do
    # not depend on the Sheet, so a Google outage should not also cost us the
    # position tracking — that would silently orphan a day of picks.
    save_state(positions)
    print(f"State saved to {STATE_PATH.relative_to(REPO)} ({len(positions)} positions).")

    spreadsheet, client_email = open_spreadsheet()
    print(f"Opened spreadsheet as {client_email}")

    write_tab(spreadsheet, "Today", today_values, header_row, style_spec)
    print("  wrote 'Today'")

    write_tab(spreadsheet, report["date"], today_values, header_row, style_spec)
    print(f"  wrote archive '{report['date']}'")

    # USER_ENTERED so the cumulative formulas evaluate rather than showing as
    # text. The detail rows below are plain values and unaffected.
    perf_ws = write_tab(spreadsheet, "Performance", perf_values, detail_first_row - 1,
                        value_input_option="USER_ENTERED")
    try:
        style_performance(perf_ws, perf_formats, block_start, detail_first_row, len(perf_values))
    except Exception as exc:  # noqa: BLE001 - numbers matter more than formats
        print(f"  warning: performance formatting failed: {exc}", file=sys.stderr)
    print(f"  wrote 'Performance' (detail starts at row {detail_first_row})")

    # Conviction 4+ ideas with tap-to-open Robinhood links. USER_ENTERED so the
    # HYPERLINK formulas render as links rather than literal text.
    try:
        import watchlist as _watchlist
        entries = _watchlist.collect(report_date)
        write_tab(spreadsheet, "Watchlist",
                  _watchlist.render_rows(entries, report_date), 5,
                  value_input_option="USER_ENTERED")
        print(f"  wrote 'Watchlist' ({len(entries)} conviction 4+ instruments)")
    except Exception as exc:  # noqa: BLE001 - never block the main publish
        print(f"  warning: watchlist tab failed: {exc}", file=sys.stderr)

    # Keep Today and Performance at the front, archives behind them.
    try:
        order = ["Today", "Watchlist", "Performance"]
        spreadsheet.reorder_worksheets(
            [spreadsheet.worksheet(t) for t in order]
            + [ws for ws in spreadsheet.worksheets() if ws.title not in order]
        )
    except Exception as exc:  # noqa: BLE001
        print(f"  warning: could not reorder tabs: {exc}", file=sys.stderr)

    print(f"Done. {len(ideas)} ideas published for {report['date']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
